#pragma region xtd generated code
// This code was generated by CMake script.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

#include "../src/main_form.hpp"
#include <xtd/startup.h>

startup_(xtd_fluid_simulation::main_form);
#pragma endregion
